# Generated by Django 4.0.5 on 2022-07-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KatakanaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.katakanaquiz')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.katakanaletter')),
            ],
        ),
        migrations.CreateModel(
            name='KatakanaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.katakanaquestion')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.katakanaletter')),
            ],
        ),
        migrations.CreateModel(
            name='HiraganaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.hiraganaquiz')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.hiraganaletter')),
            ],
        ),
        migrations.CreateModel(
            name='HiraganaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.hiraganaquestion')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.hiraganaletter')),
            ],
        ),
    ]
