# Generated by Django 4.0.5 on 2022-07-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiraganaLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KatakanaLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KatakanaLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kana', models.CharField(max_length=20)),
                ('romaji', models.CharField(max_length=20)),
                ('ex_kana', models.CharField(max_length=30)),
                ('ex_romaji', models.CharField(max_length=30)),
                ('ex_english', models.CharField(max_length=30)),
                ('ex_emoji', models.CharField(max_length=20)),
                ('strokeorder_img', models.FileField(blank=True, null=True, upload_to='images/lessons/katakana_stroke_order')),
                ('kana_img', models.FileField(blank=True, null=True, upload_to='images/lessons/katakana_kana')),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='lessons.katakanalesson')),
            ],
        ),
        migrations.CreateModel(
            name='HiraganaLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kana', models.CharField(max_length=20)),
                ('romaji', models.CharField(max_length=20)),
                ('ex_kana', models.CharField(max_length=30)),
                ('ex_romaji', models.CharField(max_length=30)),
                ('ex_english', models.CharField(max_length=30)),
                ('ex_emoji', models.CharField(max_length=20)),
                ('strokeorder_img', models.FileField(blank=True, null=True, upload_to='images/lessons/hiragana_stroke_order')),
                ('kana_img', models.FileField(blank=True, null=True, upload_to='images/lessons/hiragana_kana')),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='lessons.hiraganalesson')),
            ],
        ),
    ]
